services:
  - type: web
    name: hubspot-automation
    env: node
    region: oregon
    plan: starter
    buildCommand: npm install && cd client && npm install && npm run build && cd ..
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: hubspot-db
          property: connectionString
    autoDeploy: false

  - type: pserv
    name: hubspot-db
    env: postgresql
    region: oregon
    plan: starter
    databaseName: hubspot_automation
    databaseUser: hubspot_user